1.2.2 NOS Feeds changed
SanderKlootwijk/harbour-nednieuws pull request #7
Opened 2022-06-10 05:15 UTC by cow-n-berg

All urls have changed to nos.nl/feeds. SailJail compatibility added.

2022-06-10 21:42 UTC, Fuzzillogic reviewed
Note the tech URL is "feeds.nos.nl/nosnieuwstech", not "feeds.nos.nl/nosnieuwstech**nologie**"

2022-06-12 09:08 UTC, SanderKlootwijk requested changes
Thank you @cow-n-berg once again for your contribution! This Sailfish app sometimes gets forgotten by me. I had already updated the Ubuntu Touch NedNieuws app.

Thanks to @Fuzzillogic for reviewing the pull request. I also took a look at it. In the FirstPage.qml the URL for Tech news is indeed incorrect. It should be "http://feeds.nos.nl/nosnieuwstech". Furthermore, the CoverDelegate.qml still contains old Feedburner URLs. These URLs should change to the new feeds.nos.nl format too. If you would like to change this, I'll merge the request and put a new version of the app in the Jolla Store :)

2022-06-14 06:33 UTC, a-dekker commented on harbour-nednieuws.desktop
> +ApplicationName=news-photos
ApplicationName is not correct

2022-06-14 06:46 UTC, a-dekker commented
Please try to exclude those *.pro.user.* files in your commits/PR. They are dynamically generated and should not be part of the sourcecode.

2022-09-16 16:41 UTC, closed without merging